---

name: Respec validation
on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "docs/**"

jobs:
  build-respec:
    name: Build and Validate
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: respec
