---

name: Public respec document
on:
  push:
    branches:
      - main
jobs:
  main:
    name: Publish via Github Pages
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: w3c/spec-prod@v2
        with:
          GH_PAGES_BRANCH: gh-pages
          TOOLCHAIN: respec
          SOURCE: docs/index.html
